syntax = "proto2";
package hw.trezor.messages;

/**
 * Messages for Trezor communication
 */

/**
 * Mapping between Trezor wire identifier (uint) and a protobuf message
 */
enum MessageType {
    // Zcash
    MessageType_GetAddress = 0;
    MessageType_Address = 1;
    MessageType_GetViewingKey = 2;
    MessageType_ViewingKey = 3;
    MessageType_SignPczt = 4;
    MessageType_PcztRequest = 5;
    MessageType_PcztAck = 6;
    MessageType_SpendAuthSignatures = 7;
    MessageType_Cancel = 8;
    // Debug builds only.
    MessageType_GetDiagnostics = 9;
    MessageType_Diagnostics = 10;
}
