[project]
name = "zcash"
version = "0.1.0"
description = "Device tests of the Zcash app"
requires-python = ">=3.9, <4"

[dependency-groups]

dev = [
    "pytest>=8.4.1",
    "trezor",
    "mako>=1.0.7,<2",
    "protobuf",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

addopts = "-q"

[tool.uv.sources]
trezor = { path = "../../../python", editable = true }
